openapi: 3.0.3
info:
  title: Кредитный конвейер - OpenAPI 3.0
  description: Кредитный Конвейер. Цель проекта - реализовать бэкенд-приложение с микросервисной архитектурой - прототип небольшого банка
  contact:
    name: Андрей Гуринов
    email: tunebaker@gmail.com
  version: 1.0.11
servers:
  - url: https://localhost:8082/

tags:
  - name: application
    description: Микросервис Заявка

paths:
  /application:
    post:
      tags:
        - application
      summary: Расчёт возможных условий кредита
      operationId: createApplication
      description: Прескоринг + запрос на расчёт возможных условий кредита
      requestBody:
        required: true
        description: расчёт возможных условий кредита
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanApplicationRequestDTO'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanOfferDTO'
        '400':
          description: Invalid input
  /application/offer:
    put:
      tags:
        - application
      summary: Выбор одного из предложений
      operationId: applyOffer
      description: Выбор одного из предложений
      requestBody:
        required: true
        description: Выбор одного из предложений
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanOfferDTO'
      responses:
        default:
          description: Successful operation

components:
  schemas:
    LoanApplicationRequestDTO:
      type: object
      description: Первичный запрос на кредит
      properties:
        amount:
          type: number
          description: Желаемая сумма кредита
          format: double
          example: 15000.0
        term:
          type: integer
          description: Желаемый срок кредита в месяцах
          format: int32
          example: 12
        firstName:
          type: string
          description: Имя заемщика
          format: string
          example: Ivan
        lastName:
          type: string
          description: Фамилия заемщика
          format: string
          example: Ivanov
        middleName:
          type: string
          description: Отчество заемщика (при наличии)
          format: string
          example: Ivanovich
        email:
          type: string
          description: Email
          format: string
          example: qwe@rty.ru
        birthdate:
          type: string
          description: Дата рождения заемщика
          format: date
          example: 2000-05-09
        passportSeries:
          type: string
          description: Серия паспорта
          format: string
          example: 2003
        passportNumber:
          type: string
          description: Номер паспорта
          format: string
          example: 645979

    LoanOfferDTO:
      type: object
      description: Предварительное кредитное предложение
      properties:
        applicationId:
          type: integer
          description: Номер предложения
          format: int64
          example: 12
        requestedAmount:
          type: number
          description: Запрошенная сумма кредита
          format: double
          example: 200000.0
        totalAmount:
          type: number
          description: Рассчитанная сумма кредита с учетом страховки
          format: double
          example: 210000.0
        term:
          type: integer
          description: Продолжительность выплаты кредита в месяцах
          format: int32
          example: 36
        monthlyPayment:
          type: number
          description: Ежемесячный платёж
          format: double
          example: 1000.0
        rate:
          type: number
          description: Годовая ставка кредита
          format: double
          example: 13.5
        isInsuranceEnabled:
          type: boolean
          description: Страховка включена
        isSalaryClient:
          type: boolean
          description: Зарплатный клиент



