openapi: 3.0.3
info:
  title: Кредитный конвейер - OpenAPI 3.0
  description: Микросервис API-Gateway
  contact:
    name: Андрей Гуринов
    email: tunebaker@gmail.com
  version: 1.0.11
servers:
  - url: https://localhost:8084/


paths: {}

components:
  schemas:
    EmploymentDTO:
      type: object
      description: Данные о занятости заемщика
      properties:
        employmentStatus:
          type: string
          description: Статус занятости
          enum:
            [ EMPLOYED,
              UNEMPLOYED,
              SELF_EMPLOYED,
              BUSINESS_OWNER ]
          example: EMPLOYED
        employerINN:
          type: string
          description: ИНН
          format: string
          example: 124512457845
        salary:
          type: number
          description: Заработная плата за месяц
          format: double
          example: 15000.0
        position:
          type: string
          description: Должность
          enum:
            [ ORDINARY_WORKER,
              MIDDLE_MANAGER,
              TOP_MANAGER ]
          example: ORDINARY_WORKER
        workExperienceTotal:
          type: integer
          description: Общий стаж работы в месяцах
          format: int32
          example: 100
        workExperienceCurrent:
          type: integer
          description: Стаж работы на текущем месте в месяцах
          format: int32
          example: 15
    LoanApplicationRequestDTO:
      type: object
      description: Первичный запрос на кредит
      properties:
        amount:
          type: number
          description: Желаемая сумма кредита
          format: double
          example: 15000.0
        term:
          type: integer
          description: Желаемый срок кредита в месяцах
          format: int32
          example: 12
        firstName:
          type: string
          description: Имя заемщика
          format: string
          example: Ivan
        lastName:
          type: string
          description: Фамилия заемщика
          format: string
          example: Ivanov
        middleName:
          type: string
          description: Отчество заемщика (при наличии)
          format: string
          example: Ivanovich
        email:
          type: string
          description: Email
          format: string
          example: alandrr@ya.ru
        birthdate:
          type: string
          description: Дата рождения заемщика
          format: date
          example: 2000-05-09
        passportSeries:
          type: string
          description: Серия паспорта
          format: string
          example: 2003
        passportNumber:
          type: string
          description: Номер паспорта
          format: string
          example: 645979

    LoanOfferDTO:
      type: object
      description: Предварительное кредитное предложение
      properties:
        applicationId:
          type: integer
          description: Номер предложения
          format: int64
          example: 12
        requestedAmount:
          type: number
          description: Запрошенная сумма кредита
          format: double
          example: 200000.0
        totalAmount:
          type: number
          description: Рассчитанная сумма кредита с учетом страховки
          format: double
          example: 210000.0
        term:
          type: integer
          description: Продолжительность выплаты кредита в месяцах
          format: int32
          example: 36
        monthlyPayment:
          type: number
          description: Ежемесячный платёж
          format: double
          example: 1000.0
        rate:
          type: number
          description: Годовая ставка кредита
          format: double
          example: 13.5
        isInsuranceEnabled:
          type: boolean
          description: Страховка включена
        isSalaryClient:
          type: boolean
          description: Зарплатный клиент

    FinishRegistrationRequestDTO:
      type: object
      description: Данные для окончательного расчёта параметров кредита
      properties:
        gender:
          $ref: '#/components/schemas/Gender'
        maritalStatus:
          $ref: '#/components/schemas/MaritalStatus'
        dependentAmount:
          type: integer
          description: Количество иждивенцев
          example: 1
        passportIssueDate:
          type: string
          description: Дата выдачи паспорта
          format: date
          example: 2000-05-09
        passportIssueBranch:
          type: string
          description: Подразделение, выдавшее паспорт
          format: string
        employment:
          $ref: '#/components/schemas/EmploymentDTO'
        account:
          type: string
          description: Номер счёта заемщика
          format: string

    Gender:
      type: string
      description: Пол
      enum:
        [ MALE,
          FEMALE,
          NON_BINARY ]
      example: MALE

    MaritalStatus:
      type: string
      description: Семейный статус
      enum:
        [ SINGLE,
          MARRIED,
          DIVORCED ]
      example: SINGLE

