name: Java Credit Conveyor CI with Maven

on:
  # ручной запуск по кнопке
  workflow_dispatch:
  # запуск при пуше и ПР в указанные ветки
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    # воркфлоу запускать на этой ОС
    runs-on: ubuntu-latest

    steps:
      # репо копируется
      - name: 1. Check repo
        uses: actions/checkout@v3

      # This step uses the actions/setup-java action to configure
      # the Eclipse Temurin (Java) 17 JDK by Eclipse Adoptium
      - name: 2. Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 3.1 Build ms deal with Maven
        run: mvn -B package --file ./deal/pom.xml

      - name: 3.2 Build ms dossier with Maven
        run: mvn -B package --file ./dossier/pom.xml

      - name: 3.3 Build ms gateway with Maven
        run: mvn -B package --file ./gateway/pom.xml

      - name: 3.4 Build ms application with Maven
        run: mvn -B package --file ./application/pom.xml

      - name: 3.5 Build ms conveyor with Maven
        run: mvn -B package --file ./conveyor/pom.xml